### ISSUE TITLE
add Hanim export section to README.md

### ISSUE THREAD

**Issue by coderextreme** [Web3DConsortium/BlenderX3DSupport#7]

**Comment by vincentmarchetti** [comment]
No actionable information provided for this issue. Would propose that if anyone would like to add information to a README.md document, that you
1-- fork this github project, edit your project with proposed content, then submit a pull request
or
2 -- submit the proposed content as text to the issue discussion

**Comment by coderextreme** [comment]
HAnim export/support would just be another goal in the README.md  I will
look into a pull request, but I don’t do branches very well.  So suggested
text would be support all HAnim features that are possible within Blender’s
constraints.  Perhaps someone more knowledgeable about Blender can add
things like joint/site/segment representation in Blender,



John
